const authActions = {
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  REGISTER_LOADING: "REGISTER_LOADING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  LOGOUT: "LOGOUT",
  REMOVE_ERROR: "REMOVE_ERROR",
  REMOVE_MESSAGE: "REMOVE_MESSAGE",
  MODIFY_PROGRAMMER: "MODIFY_PROGRAMMER",
};

export default authActions;
